# Generated by Django 4.2.7 on 2024-04-03 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Comanda', '0002_carritoitem_comentario'),
    ]

    operations = [
        migrations.AddField(
            model_name='carritoitem',
            name='adicionales',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
