# Generated by Django 4.2.7 on 2024-02-22 17:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Comanda', '0002_remove_carrito_cantidad_remove_carrito_producto_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carrito',
            old_name='productos',
            new_name='items',
        ),
        migrations.AddField(
            model_name='carrito',
            name='usuario',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
