# Generated by Django 4.2.7 on 2024-04-03 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Menu', '0012_alter_producto_adicionales'),
        ('Comanda', '0003_carritoitem_adicionales'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carritoitem',
            name='adicionales',
        ),
        migrations.AddField(
            model_name='carritoitem',
            name='adicionales',
            field=models.ManyToManyField(to='Menu.adicional'),
        ),
    ]
