# Generated by Django 4.2.7 on 2024-02-22 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Comanda', '0003_rename_productos_carrito_items_carrito_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='carritoitem',
            name='sabor',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
