# Generated by Django 4.2.7 on 2024-02-23 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Comanda', '0004_carritoitem_sabor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carritoitem',
            name='cantidad',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
