# Generated by Django 4.2.7 on 2024-04-03 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Comanda', '0004_remove_carritoitem_adicionales_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carritoitem',
            name='adicionales',
        ),
        migrations.AddField(
            model_name='carritoitem',
            name='adicionales',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
