# Generated by Django 4.2.7 on 2024-04-03 05:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Menu', '0012_alter_producto_adicionales'),
        ('Comanda', '0005_remove_carritoitem_adicionales_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carritoitem',
            name='adicionales',
        ),
        migrations.AddField(
            model_name='carritoitem',
            name='adicional',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Menu.adicional'),
        ),
    ]
