# Generated by Django 4.2.7 on 2024-04-03 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Comanda', '0006_remove_carritoitem_adicionales_carritoitem_adicional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carritoitem',
            name='adicional',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
