# Generated by Django 4.2.7 on 2024-02-26 20:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Comanda', '0006_mesa_pedidodomicilio_remove_carrito_items_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidodomicilio',
            name='nombre',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='carrito',
            unique_together={('mesa', 'usuario')},
        ),
    ]
