# Generated by Django 4.2.7 on 2024-04-03 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Menu', '0012_alter_producto_adicionales'),
        ('Comanda', '0007_alter_carritoitem_adicional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carritoitem',
            name='adicional',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Menu.adicional'),
        ),
    ]
