# Generated by Django 4.2.7 on 2024-04-03 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Comanda', '0008_alter_carritoitem_adicional'),
    ]

    operations = [
        migrations.AddField(
            model_name='carritoitem',
            name='totalextra',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='carritoitem',
            name='adicional',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
