# Generated by Django 4.2.7 on 2024-02-27 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Menu', '0005_alter_producto_sabores_raw'),
        ('Comanda', '0008_alter_carrito_usuario'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='carrito',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='carrito',
            name='items',
            field=models.ManyToManyField(through='Comanda.CarritoItem', to='Menu.producto'),
        ),
        migrations.RemoveField(
            model_name='carrito',
            name='usuario',
        ),
    ]
