# Generated by Django 3.2.20 on 2024-03-07 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Comanda', '0009_alter_carrito_unique_together_carrito_items_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carritoitem',
            name='subtotal',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
