# Generated by Django 4.2.7 on 2024-02-29 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Comanda', '0009_alter_carrito_unique_together_carrito_items_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_venta', models.DateField()),
                ('hora_venta', models.TimeField()),
                ('carrito_items', models.ManyToManyField(to='Comanda.carritoitem')),
            ],
        ),
    ]
