# Generated by Django 3.2.20 on 2024-03-18 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Venta', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='pedido_domicilio',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
