# Generated by Django 4.2.7 on 2024-02-29 06:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Comanda', '0009_alter_carrito_unique_together_carrito_items_and_more'),
        ('Venta', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venta',
            name='carrito_items',
        ),
        migrations.AddField(
            model_name='venta',
            name='carrito',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Comanda.carrito'),
        ),
    ]
