# Generated by Django 3.2.20 on 2024-03-07 02:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Menu', '0005_alter_producto_sabores_raw'),
        ('Comanda', '0010_carritoitem_subtotal'),
        ('Venta', '0002_remove_venta_carrito_items_venta_carrito'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venta',
            name='carrito',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='fecha_venta',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='hora_venta',
        ),
        migrations.AddField(
            model_name='venta',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='venta',
            name='mesa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Comanda.mesa'),
        ),
        migrations.AddField(
            model_name='venta',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.CreateModel(
            name='VentaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('subtotal', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Menu.producto')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Venta.venta')),
            ],
        ),
    ]
