# Generated by Django 3.2.20 on 2024-03-18 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Venta', '0002_venta_pedido_domicilio'),
        ('Venta', '0002_ventaitem_sabor_alter_ventaitem_venta'),
    ]

    operations = [
    ]
