# Generated by Django 4.2.7 on 2024-03-01 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Venta', '0002_remove_venta_carrito_items_venta_carrito'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venta',
            name='fecha_venta',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='hora_venta',
        ),
    ]
