# Generated by Django 4.2.7 on 2024-04-03 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Venta', '0003_merge_20240317_2351'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventaitem',
            name='adicionales',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
