# Generated by Django 4.2.7 on 2024-03-05 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Venta', '0003_remove_venta_fecha_venta_remove_venta_hora_venta'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='fecha_venta',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
