# Generated by Django 4.2.7 on 2024-01-20 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='producto',
            name='sabores',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
