# Generated by Django 4.2.7 on 2024-01-20 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Menu', '0002_alter_producto_nombre_alter_producto_sabores'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='sabores',
            field=models.JSONField(blank=True, max_length=255, null=True),
        ),
    ]
