# Generated by Django 3.2.20 on 2024-02-13 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Menu', '0003_alter_producto_sabores'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='sabores',
        ),
        migrations.AddField(
            model_name='producto',
            name='sabores_raw',
            field=models.CharField(blank=True, help_text='Ingrese los sabores separados por comas', max_length=255, null=True),
        ),
    ]
