# Generated by Django 4.2.7 on 2024-04-03 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Menu', '0005_alter_producto_sabores_raw'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adicional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('precio_extra', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.AddField(
            model_name='producto',
            name='adicionales',
            field=models.ManyToManyField(blank=True, to='Menu.adicional'),
        ),
    ]
