# Generated by Django 4.2.7 on 2024-04-03 00:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Menu', '0006_adicional_producto_adicionales'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='adicionales',
        ),
        migrations.AddField(
            model_name='adicional',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='adicionales_productos', to='Menu.producto'),
        ),
    ]
