# Generated by Django 3.2.20 on 2024-04-03 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Menu', '0007_remove_producto_adicionales_adicional_producto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adicional',
            name='producto',
        ),
        migrations.AddField(
            model_name='producto',
            name='adicionales',
            field=models.ManyToManyField(blank=True, null=True, related_name='adicionales_productos', to='Menu.Adicional'),
        ),
    ]
