# Generated by Django 3.2.20 on 2024-04-03 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Menu', '0008_auto_20240402_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='adicionales',
            field=models.ManyToManyField(blank=True, related_name='adicionales_productos', to='Menu.Adicional'),
        ),
    ]
