# Generated by Django 3.2.20 on 2024-04-03 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Menu', '0009_alter_producto_adicionales'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='adicionales',
            new_name='adicionales_in',
        ),
    ]
