# Generated by Django 3.2.20 on 2024-04-03 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Menu', '0010_rename_adicionales_producto_adicionales_in'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='adicionales_in',
            new_name='adicionales',
        ),
    ]
