# Generated by Django 3.2.20 on 2024-04-03 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Menu', '0011_rename_adicionales_in_producto_adicionales'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='adicionales',
            field=models.ManyToManyField(blank=True, related_name='ingredientes_adicionales', to='Menu.Adicional'),
        ),
    ]
